# **TENSOR BASICS**
---
---

**Load Tensor**

In [3]:
import numpy as np
import torch

In [6]:
torch.__version__

'2.0.1+cu118'

---
---
## **Convert a Numpy array (VECTOR) to Tensor(1D TENSOR)**

In [7]:
# Create an Numpy Array

arr = np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

In [10]:
arr.dtype

dtype('int64')

### **Method 1**

In [14]:
# Convert Numpy Array to tensor

# Method 1

x = torch.from_numpy(arr)

In [12]:
x

tensor([1, 2, 3, 4])

In [13]:
x.dtype

torch.int64

### **Method 2**

In [16]:
# Method 2

y = torch.as_tensor(arr)

y

tensor([1, 2, 3, 4])

In [17]:
y.dtype

torch.int64

### **Method 3**

In [24]:
z = torch.tensor(arr)
z

tensor([1, 2, 3, 4])

In [25]:
z.dtype

torch.int64

### **Difference between above 3 Methods**

In [26]:
# changing the value of 1st element of numpy array

# Before Change

arr

array([1, 2, 3, 4])

In [27]:
# After Change

arr[0] = 999
arr

array([999,   2,   3,   4])

In [31]:
# Method 1 Value
x

tensor([999,   2,   3,   4])

In [32]:
# Method 2 Value
y

tensor([999,   2,   3,   4])

In [33]:
# Method 3 Value
z

tensor([1, 2, 3, 4])

if I change the value of numpy array Mehtod 1 and Method 2 Tensor change its values, as it shared same memory location

Method 3 tensor won't change, as it copy the value and use different Memory Location

---
---
## **Convert a 2d Numpy array (MATRIX) to Tensor(2D TENSOR)**

In [20]:
arr2d = np.arange(0.0, 12.0)
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [21]:
# Reshaping the array to 2D Matric

arr2d = arr2d.reshape(3,4)
arr2d


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [22]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]], dtype=torch.float64)

In [23]:
x2.dtype

torch.float64

---
---

### **Differnece Between t and T**

In [34]:
arr = np.array([1,2,3,4])

In [35]:
# Contain Integer Values

torch.tensor(arr)

tensor([1, 2, 3, 4])

In [36]:
# Contain Floating Values

torch.Tensor(arr)

tensor([1., 2., 3., 4.])

In [38]:
# Contain Floating Values

torch.FloatTensor(arr)

tensor([1., 2., 3., 4.])

---
---
## **Create Empty Cell**

In [39]:
# Empty shell with 2D tensor 2*4 Dimension

torch.empty(2,4)

tensor([[-5.0561e-26,  4.5821e-41, -8.0290e+37,  3.1906e-41],
        [ 4.4842e-44,  0.0000e+00,  1.7937e-43,  0.0000e+00]])

---
---
## **Tensor with Zero Values**

In [40]:
# By Default Data Type = Float

torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [43]:
# Zero value with Int Data Type

torch.zeros(2,3, dtype = torch.int)

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

---
---
## **Tensor with One Values**

In [44]:
torch.ones(2,3, dtype = torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

---
---
## **Create a Tensor by arranging the values between 0 to 18, gap = 2**

In [46]:
x = torch.arange(0,18,2).reshape(3,3)
x

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

---
---
## **Create a Tensor with Leanerly space valyes between 0 to 18, gap = 2**

In [53]:
x = torch.linspace(0,18,12).reshape(4,3)
x

tensor([[ 0.0000,  1.6364,  3.2727],
        [ 4.9091,  6.5455,  8.1818],
        [ 9.8182, 11.4545, 13.0909],
        [14.7273, 16.3636, 18.0000]])

---
---
## **Covert datatype of Tensors**

In [54]:
x = torch.tensor([1,2,3,4])
x

tensor([1, 2, 3, 4])

In [55]:
x.dtype

torch.int64

In [58]:
new_x = x.type(torch.float32)
new_x

tensor([1., 2., 3., 4.])

In [59]:
new_x.dtype

torch.float32