# **RANDOM VALUES**

In [2]:
import torch

---
---
## **[3,4] Tensor with Uniformly Distributed Random Values**

lower Limit = 0, higher limit = 1

In [3]:
torch.rand(3,4)

tensor([[0.8855, 0.3938, 0.8731, 0.3966],
        [0.5562, 0.1350, 0.0362, 0.4437],
        [0.3280, 0.4860, 0.3973, 0.2596]])

---
---
## **[3,4] Tensor with Normally Distributed Random Values**

Mean = 0, Standard Deviation = 1

In [4]:
torch.randn(3,4)

tensor([[ 0.3502,  0.1401,  0.7555, -0.1880],
        [-0.4194, -0.3578, -0.9040, -1.0311],
        [-0.7126, -0.0494,  0.9622,  0.8531]])

---
---
## **[3,4] Tensor Random Integer Values between 0 to 10**

In [6]:
torch.randint(low = 0, high = 11, size = (3,4))

tensor([[ 6,  7,  7,  3],
        [ 7, 10,  2,  0],
        [ 3,  7,  0,  5]])

---
---
## **[3,4] Tensor which uses shape of other tensor**

In [9]:
other_tensor = torch.zeros(3,8)

In [10]:
torch.rand_like(other_tensor)

tensor([[0.4588, 0.6183, 0.2991, 0.2285, 0.3494, 0.7367, 0.7864, 0.8702],
        [0.2862, 0.3175, 0.9231, 0.0597, 0.0551, 0.4154, 0.2005, 0.6487],
        [0.8036, 0.2778, 0.5159, 0.7231, 0.3842, 0.0700, 0.1494, 0.0046]])

In [20]:
torch.randint_like( other_tensor, low = 0, high = 11 )

tensor([[ 9.,  5.,  0.,  0.,  8.,  7.,  0.,  4.],
        [ 0.,  8.,  3., 10.,  7.,  5.,  2.,  6.],
        [ 4.,  9.,  9.,  8.,  6.,  1.,  3.,  2.]])

---
---
## **Manual Seed - same value everywhere**

In [21]:
torch.manual_seed(42)

In [22]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [23]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [24]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])