## **Tensor Operations**

In [19]:
import torch

In [4]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

### **Reshape() and view()**

In [6]:
a.reshape(2,2)

tensor([[1, 2],
        [3, 4]])

In [8]:
b.view(2,2)

tensor([[5, 6],
        [7, 8]])

In [9]:
a, b

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]))

## **Addition**

In [10]:
a + b

tensor([ 6,  8, 10, 12])

In [12]:
torch.add(a,b)

tensor([ 6,  8, 10, 12])

### **Multiplication**

In [13]:
a*b

tensor([ 5, 12, 21, 32])

In [14]:
torch.mul(a,b)

tensor([ 5, 12, 21, 32])

### **Difference between mul and mul_ (UNDERSCORE METHOD)**

In [15]:
# a = a+b

a.mul(b )

tensor([ 5, 12, 21, 32])

In [16]:
a

tensor([1, 2, 3, 4])

In [17]:
a.mul_(b)

tensor([ 5, 12, 21, 32])

In [18]:
a

tensor([ 5, 12, 21, 32])

---
---
## **Matrix Multiplication**

In [28]:
b = torch.tensor([[6,7], [8,9], [10,11]])
a = torch.tensor([[5,6,5],[5,6,7]])

In [29]:
# only possible if shape matchs correctly

# no of columns of a = no of rows of b

torch.mm(a,b)

tensor([[128, 144],
        [148, 166]])

In [30]:
a@b

tensor([[128, 144],
        [148, 166]])

### **Dot Product**

In [32]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

In [21]:
a.dot(b)

tensor(70)

## **Eucledian Norm**

In [34]:
a = torch.Tensor([1,2,3,4])
a.norm()

#norm can be derived from Floating values

tensor(5.4772)