# **PyTorch Gradients**
---
---

In [ ]:
import torch

In [ ]:

x = torch.tensor(2.0, requires_grad = True)

In [ ]:
# y is a function of x

y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
y

tensor(63., grad_fn=<AddBackward0>)

In [ ]:
type(y)

torch.Tensor

In [ ]:
y.backward()

In [ ]:
#dy/dx

y_dash = x.grad
y_dash

tensor(93.)

**Conclusion :** 93 is the slope of polynimial(dy/dx) when x = 2

---
---
### **Series of Equation - Gradient**

In [ ]:
x = torch.tensor([[1.,2.,3.],[3., 2., 1.]], requires_grad = True)
x

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)

In [ ]:
y = 3*x + 2
y

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)

In [ ]:
z = 2*y**2
z

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)

In [ ]:
out = z.mean()

In [ ]:
out

tensor(140., grad_fn=<MeanBackward0>)

In [ ]:
out.backward()

In [ ]:
x.grad

tensor([[10., 16., 22.],
        [22., 16., 10.]])