# **PyTorch DataSets**
---
---

## **Perfrom Standard Imports**

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## **Mount Google Drive**

In [41]:
from google.colab import drive

In [42]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


## **Loading Data from Files**

In [43]:
df = pd.read_csv("/content/drive/MyDrive/Jose Potilla | Pytorch/Data/iris.csv")

In [44]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [45]:
X = df.drop('target', axis = 1).values
y = df['target'].values

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 33)

### **Previous X and Y Values**

In [47]:
X_train[0:5]

array([[5.1, 2.5, 3. , 1.1],
       [4.8, 3.4, 1.6, 0.2],
       [7.9, 3.8, 6.4, 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.1, 3.7, 1.5, 0.4]])

In [48]:
y_train[0:5]

array([1., 0., 2., 0., 0.])

**Conclusion :**

* These are Numpy Arrays. Our task is to convert this numpy array into tensors

---
---
## **Method 1 - Classic Method build Train/Test Tensor**

In [49]:
import torch

In [50]:
# X Values - Continous Values - Float

X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

In [51]:
X_train[0:5]

tensor([[5.1000, 2.5000, 3.0000, 1.1000],
        [4.8000, 3.4000, 1.6000, 0.2000],
        [7.9000, 3.8000, 6.4000, 2.0000],
        [5.1000, 3.4000, 1.5000, 0.2000],
        [5.1000, 3.7000, 1.5000, 0.4000]])

In [52]:
# y Values - Categorical Values - Long

y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

# Reshape is necessary to make it Matrix

In [53]:
y_train[0:5]

tensor([[1],
        [0],
        [2],
        [0],
        [0]])

In [54]:
X_train.dtype

torch.float32

**Conclusion :**

Now Both Data are in Tensor Form

---
---
## **Method 2 - Using PyTorch's DataSet and DataLoader**

In [55]:
from torch.utils.data import TensorDataset, DataLoader

In [57]:
X = df.drop('target', axis = 1).values
y = df['target'].values

In [58]:
# Create a Tensor DataSet = Iris

iris = TensorDataset( torch.FloatTensor(X), torch.LongTensor(y))

In [59]:
type(iris)

torch.utils.data.dataset.TensorDataset

In [60]:
len(iris)

150

In [62]:
iris_loader = DataLoader(iris, batch_size = 50, shuffle = True )

In [63]:
iris_loader

In [65]:
for i in iris:
  print (i)

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0))
(tensor([5.4000, 3.7000, 1.5000, 0.2000]), tensor(0))
(tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0))
(tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0))
(tensor([4.3000, 3.0000, 1.1000, 0.1000]), tensor(0))
(tensor([5.8000, 4.0000, 1.2000, 0.2000]), tensor(0))
(tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0))
(tensor([5.4000, 3.9000, 1.3000, 0.4000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.3000]), tensor(0))
(tensor([5.7000, 3.8000, 1.7

In [66]:
  for i_batch,sample_batch in enumerate(iris_loader):
    print(i_batch, sample_batch)

0 [tensor([[6.4000, 3.1000, 5.5000, 1.8000],
        [6.7000, 3.0000, 5.0000, 1.7000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [6.7000, 3.1000, 4.7000, 1.5000],
        [5.0000, 3.5000, 1.6000, 0.6000],
        [6.3000, 2.9000, 5.6000, 1.8000],
        [6.1000, 2.8000, 4.7000, 1.2000],
        [4.4000, 2.9000, 1.4000, 0.2000],
        [6.3000, 2.3000, 4.4000, 1.3000],
        [6.4000, 2.7000, 5.3000, 1.9000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [6.0000, 3.4000, 4.5000, 1.6000],
        [4.8000, 3.0000, 1.4000, 0.3000],
        [5.2000, 2.7000, 3.9000, 1.4000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [6.4000, 3.2000, 5.3000, 2.3000],
        [5.7000, 2.9000, 4.2000, 1.3000],
        [6.8000, 3.0000, 5.5000, 2.1000],
        [5.7000, 2.8000, 4.5000, 1.3000],
        [4.6000, 3.6000, 1.0000, 0.2000],
        [5.4000, 3.7000, 1.5000, 0.2000],
        [5.5000, 2.6000, 4.4000, 1.2000],
        [5.7000, 4.4000, 1.5000, 0.4000],
        [6.5000, 3.0000, 5.2000